name: Production deploy

on:
  push:
    branches:
      - main


jobs:
  test-and-deploy-to-digitel-ocean:
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
